// flow-typed signature: db9b270cf3cb51dbd9ba443366d0cc95
// flow-typed version: <<STUB>>/blockstack_v18.0.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blockstack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blockstack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blockstack/dist/blockstack' {
  declare module.exports: any;
}

declare module 'blockstack/docs/assets/anchor' {
  declare module.exports: any;
}

declare module 'blockstack/docs/assets/site' {
  declare module.exports: any;
}

declare module 'blockstack/docs/assets/split' {
  declare module.exports: any;
}

declare module 'blockstack/lib/auth/authApp' {
  declare module.exports: any;
}

declare module 'blockstack/lib/auth/authConstants' {
  declare module.exports: any;
}

declare module 'blockstack/lib/auth/authMessages' {
  declare module.exports: any;
}

declare module 'blockstack/lib/auth/authProvider' {
  declare module.exports: any;
}

declare module 'blockstack/lib/auth/authSession' {
  declare module.exports: any;
}

declare module 'blockstack/lib/auth/authVerification' {
  declare module.exports: any;
}

declare module 'blockstack/lib/auth/index' {
  declare module.exports: any;
}

declare module 'blockstack/lib/config' {
  declare module.exports: any;
}

declare module 'blockstack/lib/dids' {
  declare module.exports: any;
}

declare module 'blockstack/lib/encryption' {
  declare module.exports: any;
}

declare module 'blockstack/lib/errors' {
  declare module.exports: any;
}

declare module 'blockstack/lib/index' {
  declare module.exports: any;
}

declare module 'blockstack/lib/keys' {
  declare module.exports: any;
}

declare module 'blockstack/lib/logger' {
  declare module.exports: any;
}

declare module 'blockstack/lib/network' {
  declare module.exports: any;
}

declare module 'blockstack/lib/operations/index' {
  declare module.exports: any;
}

declare module 'blockstack/lib/operations/safety' {
  declare module.exports: any;
}

declare module 'blockstack/lib/operations/signers' {
  declare module.exports: any;
}

declare module 'blockstack/lib/operations/skeletons' {
  declare module.exports: any;
}

declare module 'blockstack/lib/operations/txbuild' {
  declare module.exports: any;
}

declare module 'blockstack/lib/operations/utils' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/index' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profile' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileLookup' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileProofs' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileSchemas/creativework' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileSchemas/index' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileSchemas/organization' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileSchemas/person' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileSchemas/personLegacy' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileSchemas/personUtils' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileSchemas/personZoneFiles' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileTokens' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/profileZoneFiles' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/services/facebook' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/services/github' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/services/hackerNews' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/services/index' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/services/instagram' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/services/linkedIn' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/services/service' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/services/serviceUtils' {
  declare module.exports: any;
}

declare module 'blockstack/lib/profiles/services/twitter' {
  declare module.exports: any;
}

declare module 'blockstack/lib/storage/hub' {
  declare module.exports: any;
}

declare module 'blockstack/lib/storage/index' {
  declare module.exports: any;
}

declare module 'blockstack/lib/utils' {
  declare module.exports: any;
}

declare module 'blockstack/tests/authTests/lib/index' {
  declare module.exports: any;
}

declare module 'blockstack/tests/authTests/src/index' {
  declare module.exports: any;
}

declare module 'blockstack/tests/browserTests/auth-server' {
  declare module.exports: any;
}

declare module 'blockstack/tests/browserTests/auth/app' {
  declare module.exports: any;
}

declare module 'blockstack/tests/browserTests/proofs-server' {
  declare module.exports: any;
}

declare module 'blockstack/tests/operationsTests/lib/index' {
  declare module.exports: any;
}

declare module 'blockstack/tests/operationsTests/lib/operationsTests' {
  declare module.exports: any;
}

declare module 'blockstack/tests/operationsTests/src/index' {
  declare module.exports: any;
}

declare module 'blockstack/tests/operationsTests/src/operationsTests' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/index' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/sampleData' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/unitTestsAuth' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/unitTestsEncryption' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/unitTestsErrors' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/unitTestsOperations' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/unitTestsProfiles' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/unitTestsProofs' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/unitTestsStorage' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/lib/unitTestsUtils' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/index' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/sampleData' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/unitTestsAuth' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/unitTestsEncryption' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/unitTestsErrors' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/unitTestsOperations' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/unitTestsProfiles' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/unitTestsProofs' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/unitTestsStorage' {
  declare module.exports: any;
}

declare module 'blockstack/tests/unitTests/src/unitTestsUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blockstack/dist/blockstack.js' {
  declare module.exports: $Exports<'blockstack/dist/blockstack'>;
}
declare module 'blockstack/docs/assets/anchor.js' {
  declare module.exports: $Exports<'blockstack/docs/assets/anchor'>;
}
declare module 'blockstack/docs/assets/site.js' {
  declare module.exports: $Exports<'blockstack/docs/assets/site'>;
}
declare module 'blockstack/docs/assets/split.js' {
  declare module.exports: $Exports<'blockstack/docs/assets/split'>;
}
declare module 'blockstack/lib/auth/authApp.js' {
  declare module.exports: $Exports<'blockstack/lib/auth/authApp'>;
}
declare module 'blockstack/lib/auth/authConstants.js' {
  declare module.exports: $Exports<'blockstack/lib/auth/authConstants'>;
}
declare module 'blockstack/lib/auth/authMessages.js' {
  declare module.exports: $Exports<'blockstack/lib/auth/authMessages'>;
}
declare module 'blockstack/lib/auth/authProvider.js' {
  declare module.exports: $Exports<'blockstack/lib/auth/authProvider'>;
}
declare module 'blockstack/lib/auth/authSession.js' {
  declare module.exports: $Exports<'blockstack/lib/auth/authSession'>;
}
declare module 'blockstack/lib/auth/authVerification.js' {
  declare module.exports: $Exports<'blockstack/lib/auth/authVerification'>;
}
declare module 'blockstack/lib/auth/index.js' {
  declare module.exports: $Exports<'blockstack/lib/auth/index'>;
}
declare module 'blockstack/lib/config.js' {
  declare module.exports: $Exports<'blockstack/lib/config'>;
}
declare module 'blockstack/lib/dids.js' {
  declare module.exports: $Exports<'blockstack/lib/dids'>;
}
declare module 'blockstack/lib/encryption.js' {
  declare module.exports: $Exports<'blockstack/lib/encryption'>;
}
declare module 'blockstack/lib/errors.js' {
  declare module.exports: $Exports<'blockstack/lib/errors'>;
}
declare module 'blockstack/lib/index.js' {
  declare module.exports: $Exports<'blockstack/lib/index'>;
}
declare module 'blockstack/lib/keys.js' {
  declare module.exports: $Exports<'blockstack/lib/keys'>;
}
declare module 'blockstack/lib/logger.js' {
  declare module.exports: $Exports<'blockstack/lib/logger'>;
}
declare module 'blockstack/lib/network.js' {
  declare module.exports: $Exports<'blockstack/lib/network'>;
}
declare module 'blockstack/lib/operations/index.js' {
  declare module.exports: $Exports<'blockstack/lib/operations/index'>;
}
declare module 'blockstack/lib/operations/safety.js' {
  declare module.exports: $Exports<'blockstack/lib/operations/safety'>;
}
declare module 'blockstack/lib/operations/signers.js' {
  declare module.exports: $Exports<'blockstack/lib/operations/signers'>;
}
declare module 'blockstack/lib/operations/skeletons.js' {
  declare module.exports: $Exports<'blockstack/lib/operations/skeletons'>;
}
declare module 'blockstack/lib/operations/txbuild.js' {
  declare module.exports: $Exports<'blockstack/lib/operations/txbuild'>;
}
declare module 'blockstack/lib/operations/utils.js' {
  declare module.exports: $Exports<'blockstack/lib/operations/utils'>;
}
declare module 'blockstack/lib/profiles/index.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/index'>;
}
declare module 'blockstack/lib/profiles/profile.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profile'>;
}
declare module 'blockstack/lib/profiles/profileLookup.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileLookup'>;
}
declare module 'blockstack/lib/profiles/profileProofs.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileProofs'>;
}
declare module 'blockstack/lib/profiles/profileSchemas/creativework.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileSchemas/creativework'>;
}
declare module 'blockstack/lib/profiles/profileSchemas/index.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileSchemas/index'>;
}
declare module 'blockstack/lib/profiles/profileSchemas/organization.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileSchemas/organization'>;
}
declare module 'blockstack/lib/profiles/profileSchemas/person.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileSchemas/person'>;
}
declare module 'blockstack/lib/profiles/profileSchemas/personLegacy.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileSchemas/personLegacy'>;
}
declare module 'blockstack/lib/profiles/profileSchemas/personUtils.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileSchemas/personUtils'>;
}
declare module 'blockstack/lib/profiles/profileSchemas/personZoneFiles.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileSchemas/personZoneFiles'>;
}
declare module 'blockstack/lib/profiles/profileTokens.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileTokens'>;
}
declare module 'blockstack/lib/profiles/profileZoneFiles.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/profileZoneFiles'>;
}
declare module 'blockstack/lib/profiles/services/facebook.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/services/facebook'>;
}
declare module 'blockstack/lib/profiles/services/github.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/services/github'>;
}
declare module 'blockstack/lib/profiles/services/hackerNews.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/services/hackerNews'>;
}
declare module 'blockstack/lib/profiles/services/index.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/services/index'>;
}
declare module 'blockstack/lib/profiles/services/instagram.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/services/instagram'>;
}
declare module 'blockstack/lib/profiles/services/linkedIn.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/services/linkedIn'>;
}
declare module 'blockstack/lib/profiles/services/service.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/services/service'>;
}
declare module 'blockstack/lib/profiles/services/serviceUtils.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/services/serviceUtils'>;
}
declare module 'blockstack/lib/profiles/services/twitter.js' {
  declare module.exports: $Exports<'blockstack/lib/profiles/services/twitter'>;
}
declare module 'blockstack/lib/storage/hub.js' {
  declare module.exports: $Exports<'blockstack/lib/storage/hub'>;
}
declare module 'blockstack/lib/storage/index.js' {
  declare module.exports: $Exports<'blockstack/lib/storage/index'>;
}
declare module 'blockstack/lib/utils.js' {
  declare module.exports: $Exports<'blockstack/lib/utils'>;
}
declare module 'blockstack/tests/authTests/lib/index.js' {
  declare module.exports: $Exports<'blockstack/tests/authTests/lib/index'>;
}
declare module 'blockstack/tests/authTests/src/index.js' {
  declare module.exports: $Exports<'blockstack/tests/authTests/src/index'>;
}
declare module 'blockstack/tests/browserTests/auth-server.js' {
  declare module.exports: $Exports<'blockstack/tests/browserTests/auth-server'>;
}
declare module 'blockstack/tests/browserTests/auth/app.js' {
  declare module.exports: $Exports<'blockstack/tests/browserTests/auth/app'>;
}
declare module 'blockstack/tests/browserTests/proofs-server.js' {
  declare module.exports: $Exports<'blockstack/tests/browserTests/proofs-server'>;
}
declare module 'blockstack/tests/operationsTests/lib/index.js' {
  declare module.exports: $Exports<'blockstack/tests/operationsTests/lib/index'>;
}
declare module 'blockstack/tests/operationsTests/lib/operationsTests.js' {
  declare module.exports: $Exports<'blockstack/tests/operationsTests/lib/operationsTests'>;
}
declare module 'blockstack/tests/operationsTests/src/index.js' {
  declare module.exports: $Exports<'blockstack/tests/operationsTests/src/index'>;
}
declare module 'blockstack/tests/operationsTests/src/operationsTests.js' {
  declare module.exports: $Exports<'blockstack/tests/operationsTests/src/operationsTests'>;
}
declare module 'blockstack/tests/unitTests/lib/index.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/index'>;
}
declare module 'blockstack/tests/unitTests/lib/sampleData.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/sampleData'>;
}
declare module 'blockstack/tests/unitTests/lib/unitTestsAuth.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/unitTestsAuth'>;
}
declare module 'blockstack/tests/unitTests/lib/unitTestsEncryption.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/unitTestsEncryption'>;
}
declare module 'blockstack/tests/unitTests/lib/unitTestsErrors.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/unitTestsErrors'>;
}
declare module 'blockstack/tests/unitTests/lib/unitTestsOperations.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/unitTestsOperations'>;
}
declare module 'blockstack/tests/unitTests/lib/unitTestsProfiles.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/unitTestsProfiles'>;
}
declare module 'blockstack/tests/unitTests/lib/unitTestsProofs.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/unitTestsProofs'>;
}
declare module 'blockstack/tests/unitTests/lib/unitTestsStorage.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/unitTestsStorage'>;
}
declare module 'blockstack/tests/unitTests/lib/unitTestsUtils.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/lib/unitTestsUtils'>;
}
declare module 'blockstack/tests/unitTests/src/index.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/index'>;
}
declare module 'blockstack/tests/unitTests/src/sampleData.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/sampleData'>;
}
declare module 'blockstack/tests/unitTests/src/unitTestsAuth.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/unitTestsAuth'>;
}
declare module 'blockstack/tests/unitTests/src/unitTestsEncryption.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/unitTestsEncryption'>;
}
declare module 'blockstack/tests/unitTests/src/unitTestsErrors.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/unitTestsErrors'>;
}
declare module 'blockstack/tests/unitTests/src/unitTestsOperations.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/unitTestsOperations'>;
}
declare module 'blockstack/tests/unitTests/src/unitTestsProfiles.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/unitTestsProfiles'>;
}
declare module 'blockstack/tests/unitTests/src/unitTestsProofs.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/unitTestsProofs'>;
}
declare module 'blockstack/tests/unitTests/src/unitTestsStorage.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/unitTestsStorage'>;
}
declare module 'blockstack/tests/unitTests/src/unitTestsUtils.js' {
  declare module.exports: $Exports<'blockstack/tests/unitTests/src/unitTestsUtils'>;
}
